// <copyright file="RefLocation.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// <autogenerated />
// </copyright>
// <autogenerated />

namespace Teakorigin.Domain.Model
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class AnalyteUom
    {
        [Column("analyte_name")]
        [Key]
        public string AnalyteName { get; set; }

        [Column("uom")]
        public string Uom { get; set; }

    }
}
