// <copyright file="RetailerRanks.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// <autogenerated />
// </copyright>
// <autogenerated />

namespace Teakorigin.Domain.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using Newtonsoft.Json;

    [Serializable]
    public partial class RetailerRanks
    {
        public string RetailerCode { get; set; }

        [JsonIgnore]
        public double QualAvg { get; set; }

        /// <summary>
        /// Gets or sets the Quality in output.
        /// </summary>
        /// <value>
        /// The total value rank.
        /// </value>
        [JsonProperty("quality")]
        public int Quality
        {
            get
            {
                return (int)Math.Round(this.QualAvg, 0, MidpointRounding.AwayFromZero);
            }
        }

        [JsonIgnore]
        public long TotalValueRank { get; set; }

        /// <summary>
        /// Gets or sets the actual value rank. The value param in output.
        /// </summary>
        /// <value>
        /// The actual value rank.
        /// </value>
        [JsonIgnore]
        public long ActualValueRank { get; set; }

        /// <summary>
        /// Gets the value.
        /// </summary>
        /// <value>
        /// The value.
        /// </value>
        public long Value
        {
            get
            {
                return this.ActualValueRank;
            }
        }

        [JsonIgnore]
        public string LocationCode { get; set; }

        [JsonIgnore]
        public int PerceptionScore { get; set; }

        /// <summary>
        /// Gets the perception.
        /// </summary>
        /// <value>
        /// The perception.
        /// </value>
        public int Perception
        {
            get
            {
                return this.PerceptionScore;
            }
        }

        [NotMapped]
        public bool QualityChampion { get; set; }

        [NotMapped]
        public bool ValueChampion { get; set; }

        [NotMapped]
        public bool PerceptionChampion { get; set; }

        /// <summary>
        /// Gets or sets the country of origin.
        /// </summary>
        /// <value>
        /// The country of origin.
        /// </value>
        [JsonIgnore]
        [NotMapped]
        public string CountryOfOrigin { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is organic.
        /// </summary>
        /// <value>
        ///   <c>true</c> if this instance is organic; otherwise, <c>false</c>.
        /// </value>
        [JsonIgnore]
        [NotMapped]
        public bool IsOrganic { get; set; }

        public List<CountryOfOrigin> CountriesOfOrigin { get; set; }
    }

    public class CountryOfOrigin
    {
        public string CountryName { get; set; }

        public bool IsOrganic { get; set; }
    }
}