export const API = 'API';

export const CONTENT_ERROR = 'CONTENT_ERROR';
export const CONTENT_FETCHED = 'CONTENT_FETCHED';
export const SET_FOOTER_CONTENT = 'SET_FOOTER_CONTENT';
export const SET_VIEWPORT = 'SET_VIEWPORT';
export const SET_NOT_FOUND_SCREENS = 'SET_NOT_FOUND_SCREENS';
export const SET_RETAILER_PROFILE_CONTENT = 'SET_RETAILER_PROFILE_CONTENT';
export const SET_PRODUCE_PROFILE_CONTENT = 'SET_PRODUCE_PROFILE_CONTENT';
export const SET_HOMEPAGE_CONTENT  = 'SET_HOMEPAGE_CONTENT';
export const SET_HOMEPAGE_SLIDES_CONTENT = 'SET_HOMEPAGE_SLIDES_CONTENT';
export const SET_FILTERS_CONTENT = 'SET_FILTERS_CONTENT';
export const SET_PRODUCE_BASKET_CONTENT = 'SET_PRODUCE_BASKET_CONTENT';
export const SET_SUBSCRIBE_CONTENT = 'SET_SUBSCRIBE_CONTENT';
export const SET_TOOLTIPS_CONTENT = 'SET_TOOLTIPS_CONTENT';
export const SET_SOCIAL_LINKS_CONTENT = 'SET_SOCIAL_LINKS_CONTENT';
export const SET_BREADCRUMBS_CONTENT = 'SET_BREADCRUMBS_CONTENT';
export const SET_HEADER_CONTENT = 'SET_HEADER_CONTENT';
export const SET_OVERALL_RANK_CONTENT = 'SET_OVERALL_RANK_CONTENT';
export const SET_BUTTONS_CONTENT = 'SET_BUTTONS_CONTENT';
export const SET_COOKIE_BANNER_CONTENT = 'SET_COOKIE_BANNER_CONTENT';
export const SET_METADATA_CONTENT = 'SET_METADATA_CONTENT';

export const SET_INITIAL_PRODUCES = 'SET_INITIAL_PRODUCES';
export const UPDATE_PRODUCE = 'UPDATE_PRODUCE';
export const SELECT_ALL_PRODUCES_CHECKBOX = 'SELECT_ALL_PRODUCES_CHECKBOX';
export const SELECT_ALL_PRODUCES = 'SELECT_ALL_PRODUCES';
export const SET_PRODUCES_CONTENT = 'SET_PRODUCES_CONTENT';
export const SET_PRODUCE_DATA = 'SET_PRODUCE_DATA';
export const SET_SELECTED_PRODUCE = 'SET_SELECTED_PRODUCE';

export const UPDATE_RETAILER = 'UPDATE_RETAILER';
export const SELECT_ALL_RETAILERS_CHECKBOX = 'SELECT_ALL_RETAILERS_CHECKBOX';
export const SELECT_ALL_RETAILERS = 'SELECT_ALL_RETAILERS';
export const SET_SELECTED_RETAILER = 'SET_SELECTED_RETAILER';
export const SET_INITIAL_RETAILERS = 'SET_INITIAL_RETAILERS';
export const SET_RETAILERS_CONTENT = 'SET_RETAILERS_CONTENT';
export const SET_RETAILERS_DATA = 'SET_RETAILERS_DATA';;

export const SET_SORT_RANKS = 'SET_SORT_RANKS';
export const SET_RETAILERS_TABLE = 'SET_RETAILERS_TABLE';
export const SET_RANKED_RETAILER = 'SET_RANKED_RETAILER';
export const SET_RANKED_RETAILER_SINGLE = 'SET_RANKED_RETAILER_SINGLE';
export const SET_INITIAL_RANKED_COMPARE_BY= 'SET_INITIAL_RANKED_COMPARE_BY';

export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const SET_RETAILER_PRODUCES = 'SET_RETAILER_PRODUCES';
export const SET_RETAILER_PRODUCES_COMPAREBY = 'SET_RETAILER_PRODUCES_COMPAREBY';
export const UPDATE_RETAILER_PRODUCES = 'UPDATE_RETAILER_PRODUCES';
export const SET_RETAILER_PRODUCES_SORT = 'SET_RETAILER_PRODUCES_SORT'
export const SET_PRODUCT_CARD_LABELS = 'SET_PRODUCT_CARD_LABELS';
export const SET_PRODUCE_INFO_TABLE = 'SET_PRODUCE_INFO_TABLE';

export const SET_PRODUCE_INFO = 'SET_PRODUCE_INFO';

export const SET_PRODUCE_INFO_ANALYTES_CONTENT = 'SET_PRODUCE_INFO_ANALYTES_CONTENT';

export const SET_USDA_CONTENT = 'SET_USDA_CONTENT';
export const SET_RETAILER_TRENDS = 'SET_RETAILER_TRENDS'
export const SET_RETAILER_TRENDS_CONTENT = 'SET_RETAILER_TRENDS_CONTENT'
export const SET_RETAILER_TRENDS_VIEW = 'SET_RETAILER_TRENDS_VIEW';
export const SET_RETAILER_TRENDS_COMPARE_BY = 'SET_RETAILER_TRENDS_COMPARE_BY';
export const SET_RETAILER_TRENDS_LOADING = 'SET_RETAILER_TRENDS_LOADING';

export const SET_PRODUCE_TRENDS = 'SET_PRODUCE_TRENDS';
export const SET_PRODUCE_TRENDS_CONTENT = 'SET_PRODUCE_TRENDS_CONTENT'
export const SET_PRODUCE_TRENDS_VIEW = 'SET_PRODUCE_TRENDS_VIEW';
export const SET_PRODUCE_TRENDS_LOADING = 'SET_PRODUCE_TRENDS_LOADING';
export const SET_PRODUCE_TRENDS_COMPARE_BY = 'SET_PRODUCE_TRENDS_COMPARE_BY';

export const SET_BEST_PICKS_CONTENT = 'SET_BEST_PICKS_CONTENT';
export const SET_MATCH_CARDS_CONTENT = 'SET_MATCH_CARDS_CONTENT';

export const SET_BEST_PICKS = 'SET_BEST_PICKS';
export const SORT_BEST_PICKS = 'SORT_BEST_PICKS';
export const SET_INITIAL_BEST_PICKS_CRITERIA = 'SET_INITIAL_BEST_PICKS_CRITERIA';

export const SET_BREADCRUMBS = 'SET_BREADCRUMBS';
