// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Lowercase needed.", Scope = "member", Target = "~M:Teakorigin.App.Controllers.UploadController.Process(Microsoft.AspNetCore.Http.IFormFile)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Lowercase needed.", Scope = "member", Target = "~P:Teakorigin.App.Models.TopPicksDetails.Analytes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1052:Static holder types should be Static or NotInheritable", Justification = "n.et core class.", Scope = "type", Target = "~T:Teakorigin.App.Program")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Needed for the upload process.", Scope = "member", Target = "~M:Teakorigin.App.Controllers.UploadController.Index(Microsoft.AspNetCore.Http.IFormFile)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "Not needed as it's non UI project.", Scope = "module")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Required.", Scope = "member", Target = "~M:Teakorigin.App.Controllers.LocationUploadController.Index(Microsoft.AspNetCore.Http.IFormFile)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Required.", Scope = "member", Target = "~M:Teakorigin.App.Extentions.ContextExtentions.GetMaxScanDateWeekend(Teakorigin.DataAccess.TeakOriginContext,System.String,Microsoft.Extensions.Caching.Distributed.IDistributedCache)~System.DateTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Required.", Scope = "member", Target = "~M:Teakorigin.App.Extentions.ContextExtentions.GetValidProduceCodes(Teakorigin.DataAccess.TeakOriginContext)~System.Threading.Tasks.Task{System.Collections.Generic.IList{Teakorigin.Domain.Model.LocationProduce}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Supression is okay here", Scope = "member", Target = "~M:Teakorigin.App.Controllers.UploadController.Index(Microsoft.AspNetCore.Http.IFormFile)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Supression is okay here", Scope = "member", Target = "~M:Teakorigin.App.Controllers.LocationUploadController.Process(Microsoft.AspNetCore.Http.IFormFile)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Supression is okay here", Scope = "member", Target = "~M:Teakorigin.App.Controllers.UploadController.Process(Microsoft.AspNetCore.Http.IFormFile)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Supression is okay here", Scope = "member", Target = "~M:Teakorigin.App.Controllers.LocationUploadController.Index(Microsoft.AspNetCore.Http.IFormFile)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Supression is okay here", Scope = "member", Target = "~M:Teakorigin.App.Controllers.CacheController.Process~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Supression is okay here", Scope = "member", Target = "~M:Teakorigin.App.Controllers.CacheController.Process~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
