// <copyright file="Startup.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// <autogenerated />
// </copyright>

namespace Teakorigin.App
{
    using System;
    using System.IO;
    using System.Reflection;
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Authentication.Cookies;
    using Microsoft.AspNetCore.Authentication.OpenIdConnect;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.HttpOverrides;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Logging;
    using Swashbuckle.AspNetCore.Swagger;
    using Teakorigin.App.Extentions;
    using Teakorigin.Business.Services;
    using Teakorigin.DataAccess;
    using Teakorigin.Domain.Interfaces;
    using Teakorigin.Domain.Models;

    /// <summary>
    /// .The startup class.
    /// </summary>
    public class Startup
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Startup"/> class.
        /// </summary>
        /// <param name="configuration">Configuration parameters.</param>
        public Startup(IConfiguration configuration, ILogger<Startup> logger)
        {
            this.Configuration = configuration;
            this.logger = logger;
        }

        /// <summary>
        /// Gets the configuration.
        /// </summary>
        /// <value>
        /// The configuration.
        /// </value>
        public IConfiguration Configuration { get; }

        private readonly ILogger<Startup> logger;

        /// <summary>
        /// // This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        /// <param name="services">Services collection.</param>
        public void ConfigureServices(IServiceCollection services)
        {
            // The order on how services are configured doesn't really matter, but is good practice to group them acording to relevance e.g: services, MVC configuration, Database, API..
            services.AddHttpClient<IContentService, ContentService>();

            services.AddHttpClient<ISubscriptionService, SendgridSubscriptionService>();

            services.AddApplicationInsightsTelemetry();


            // Data access
            services.AddDbContext<TeakOriginContext>(
                opts => opts.UseSqlServer(this.Configuration["ConnectionString:DefaultConnection"], 
                providerOptions => providerOptions.EnableRetryOnFailure()));

            // MVC Services
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            services.AddMvc().AddJsonOptions(options =>
            {
                options.SerializerSettings.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());
                options.SerializerSettings.NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore;
            });


            services.AddMvcCore().AddApiExplorer();

            // Binds appsettings.json to AppSettings.cs, and makes it available for constructor injection in our services/controllers.
            services.ConfigurePoco(this.Configuration.GetSection("AppSettings"), () => new AppSettings());

            // Register the Swagger generator, defining 1 or more Swagger documents
            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new Info { Title = "TeakOrigin API", Version = "v1" });

                // Get xml comments path
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

                // Set xml path
                options.IncludeXmlComments(xmlPath);

                options.DocInclusionPredicate((_, api) => !string.IsNullOrWhiteSpace(api.GroupName));

#pragma warning disable CS0618 // Type or member is obsolete
                options.TagActionsBy(api => api.GroupName);
#pragma warning restore CS0618 // Type or member is obsolete

                options.DescribeAllEnumsAsStrings();
            });


            // The 'AddDistributedCache' is an service configuration extenstion custom designed to read the property 'UseDistributedSqlServerCache' from the 'appsetting.json' configuration to
            // determining which cache provider to use in the application: 'AddDistributedMemoryCache' or 'AddDistributedSqlServerCache'. (Check the logic 'AddDistributedCache' in 'ServiceExtensions.cs' to see how it works)
            // We have commend use "AddDistributedMemoryCache" for "Local Development" and "UseDistributedSqlServerCache" for everything else.
            // For more information please refer to:
            // https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2
            // https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2
            services.AddDistributedCache(options => this.Configuration.Bind("AppSettings", options), options => this.Configuration.Bind("ConnectionString", options));

            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto | ForwardedHeaders.XForwardedHost;
                options.KnownNetworks.Clear();
                options.KnownProxies.Clear();

            });

            // Configure the Cross-origin resource sharing (CORS) policy
            services.AddCors(
                options =>
                {
                    options.AddPolicy(
                        "DefaultPolicy",
                        builder => builder
                            .AllowAnyOrigin()
                            .AllowAnyMethod()
                            .AllowAnyHeader()
                            .AllowCredentials());
                });

            // We configure the services that relay on Cookies to allow non-essential cookies is needed for a given request
            // B2C use cookies and we don't want to ask the user's consent to set one.
            services.Configure<CookiePolicyOptions>(
                options =>
                {
                    // This determines whether user consent for non-essential cookies is needed for a given request.
                    options.CheckConsentNeeded = context => false;
                    options.MinimumSameSitePolicy = SameSiteMode.None;
                });

            // Adds services required for application session state.
            // This just tells the app, if cookies are create.
            services.AddSession(
                options =>
                {
                    options.Cookie.Name = ".TeakOrigin.Session";
                    options.Cookie.IsEssential = true;
                });

            services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
                .AddAzureAd(options => Configuration.Bind("AzureAd", options))
                .AddCookie();

            services.AddAuthorization(options =>
            {
                options.AddPolicy("Ingestion", (AuthorizationPolicyBuilder builder) => builder?.RequireClaim("groups", this.Configuration["AppSettings:AuthConfig:IngestorGroupId"]));
            });
        }

        /// <summary>
        /// // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// </summary>
        /// <param name="app">The app name.</param>
        /// <param name="env">The environment name.</param>
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            UpdateDatabase(app);

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
            // Keep in mind the order of middleware matter and is important to know the order they are processed in the pipeline.
            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.), specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "TeakOrigin Data API V1");
            });

            app.UseForwardedHeaders();

            app.UseStaticFiles();

            // Here we tel the app which Cross-origin resource sharing (CORS) policy.
            app.UseCors("DefaultPolicy");

            // Enables static file serving for the current request path
            app.UseStaticFiles();

            // Adds the AuthenticationMiddleware which enables authentication capabilities.
            app.UseAuthentication();

            // Adds the CookiePolicyMiddleware handler to the specified, which enables cookie policy capabilities.
            app.UseCookiePolicy();

            // Adds the SessionMiddleware to automatically enable session state for the application.
            app.UseSession();

            app.UseMvc(routes =>
            {
                routes.MapRoute("default", "{controller=Home}/{action=Index}/{id?}");
            });
        }

        private static void UpdateDatabase(IApplicationBuilder app)
        {
            using (var serviceScope = app.ApplicationServices
                .GetRequiredService<IServiceScopeFactory>()
                .CreateScope())
            {
                using (var context = serviceScope.ServiceProvider.GetService<TeakOriginContext>())
                {
                    context.Database.Migrate();
                }
            }
        }
    }
}
