// <copyright file="SubscriptionPayload.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// <autogenerated />
// </copyright>

namespace Teakorigin.Domain.Models.Payloads
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// Subscription payload.
    /// </summary>
    public class SubscriptionPayload
    {
        [JsonProperty("list_ids")]
        public List<string> ListIds { get; set; }

        [JsonProperty("contacts")]
        public List<Contact> Contacts { get; set; }
    }

    /// <summary>
    /// Contact class.
    /// </summary>
    public class Contact
    {
        [JsonProperty("email")]
        public string Email { get; set; }
    }
}
