apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ecom-editor-web
spec:
  maxReplicas: {{ '5' if env['NAMESPACE'] == 'production' else '3' }}
  minReplicas: {{ '2' if env['NAMESPACE'] == 'production' else '1' }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: ecom-editor-web
  targetCPUUtilizationPercentage: '80'
