// <copyright file="AppSettings.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// <auto-generated />

namespace Teakorigin.Domain.Models
{
    /// <summary>
    /// Appsettings.
    /// </summary>
    public class AppSettings
    {
        public ContentServiceConfig ContentServiceConfig { get; set; }

        public AuthConfig AuthConfig { get; set; }

        public string AdvancedSiteUrl { get; set; }
        public string SubscriptionServiceUrl { get; set; }
        public string SubscriptionListId { get; set; }
        public string SubscriptionToken { get; set; }
        public string BaseUrl { get; set; }
        
        /// <summary>
        /// Gets or sets the cache configuration.
        /// </summary>
        /// <value>
        /// The cache configuration.
        /// </value>
        public CacheConfig CacheConfig { get; set; }

        public class ConnectionString
        {
            public string DefaultConnection { get; set; }
        }
    }

    public class AuthConfig
    {
        public string IngestorGroupId { get; set; }

        public string BlobStorageConnectionString { get; set; }
        public string IngestContainerName { get; set; }
    }

    public class ContentServiceConfig
    {
        public string ApiBaseAddressUrl { get; set; }
    }

    /// <summary>
    /// Cache config.
    /// </summary>
    public class CacheConfig
    {
        /// <summary>
        /// Gets or sets a value indicating whether [use distributed SQL server cache].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [use distributed SQL server cache]; otherwise, <c>false</c>.
        /// </value>
        public bool UseDistributedSqlServerCache { get; set; }

        /// <summary>
        /// Gets or sets the database cache table.
        /// </summary>
        /// <value>
        /// The database cache table.
        /// </value>
        public string DbCacheTable { get; set; }
    }
}
