// <copyright file="LocationRetailer.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// <autogenerated />

namespace Teakorigin.Domain.Model
{
    using Newtonsoft.Json;
    using System;

    [Serializable]
    public partial class LocationRetailer
    {
        public long Id { get; set; }

        public string LocationCode { get; set; }

        public string RetailerCode { get; set; }

        [JsonIgnore]
        public virtual Location LocationCodeNavigation { get; set; }

        [JsonIgnore]
        public virtual Retailer RetailerCodeNavigation { get; set; }
    }
}
