// <copyright file="LocationProduce.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// <autogenerated />

namespace Teakorigin.Domain.Model
{
    using Newtonsoft.Json;

    public partial class LocationProduce
    {
        public long Id { get; set; }

        public string LocationCode { get; set; }

        public string ProduceCode { get; set; }

        [JsonIgnore]
        public virtual Location LocationCodeNavigation { get; set; }

        [JsonIgnore]
        public virtual Produce Produce { get; set; }
    }
}
